学習管理アプリ
Tekkun-0116/05_learning_plan pull request #1
Opened 2020-02-13 16:50 UTC by Tekkun-0116

課題の途中でわからないところが出てきました。
【わからないこと】
①<h2>未達成</h2>
  <ul>
    <?php foreach ($notyet_plans as $plan) : ?>
⬆notyet_tasksにしたらちゃんと表示されるのですが、notyet_plansにした途端表示されなくなります。これはどういったことが原因なのでしょうか？

②編集の部分で、前まではHTML,CSSのchapter1~5まで完了が編集のところにも引き継いで乗っていたのですがどこかを触った時点で出てこなくなってしまいました。これもどういったことが原因でしょうか？

③サイトに繋いだ時点ではエラーが出ているのですが、追加のボタンを押すとタスク名が変更されていませんとちゃんと赤文字が出てきます。これはどうすればよいでしょうか？

少しわかりにくい質問かもしれませんが、ご教示よろしくおねがいします！

①の画像
![スクリーンショット 2020-02-14 1 38 53](https://user-images.githubusercontent.com/58411036/74457858-2dfbe800-4ecc-11ea-9c22-3cd32c2b12d2.png)
②の画像
![スクリーンショット 2020-02-14 1 39 03](https://user-images.githubusercontent.com/58411036/74457892-3b18d700-4ecc-11ea-80e7-1a63d6871c02.png)
③の画像
![スクリーンショット 2020-02-14 1 46 18](https://user-images.githubusercontent.com/58411036/74457913-43711200-4ecc-11ea-9260-1389b475acc9.png)
![スクリーンショット 2020-02-14 1 46 29](https://user-images.githubusercontent.com/58411036/74457919-45d36c00-4ecc-11ea-8596-5b49bf45ebf5.png)

2020-02-14 01:36 UTC, kazu-taka requested changes
@Tekkun-0116 
コメントしたので確認お願いします:bow:

2020-02-14 01:36 UTC, kazu-taka commented on index.php
> +$done_plans = $stmt->fetchAll(PDO::FETCH_ASSOC);
@Tekkun-0116 
ここでvar_dump($done_plans)をするとどうなりますか！？
コード的には問題なさそうな気がするので^^;

2020-02-14 01:36 UTC, kazu-taka commented on index.php
> +$done_plans = $stmt->fetchAll(PDO::FETCH_ASSOC);
@Tekkun-0116 
さっきのコメントは無視して下さい笑

2020-02-14 01:36 UTC, kazu-taka commented on index.php
> +$notyet_tasks = $stmt->fetchAll(PDO::FETCH_ASSOC);
@Tekkun-0116 
foreachではnotyet_plansを参照しているのに、ここではnotyet_tasksにデータを入れているので、表示されていない状態になっています！

2020-02-14 01:36 UTC, kazu-taka commented on edit.php
> +    <input type="text" name="title" id="" value="<?php echo h($plan['title']); ?>">
@Tekkun-0116 
データを入れている変数が$taskですが、ここで参照している変数は$planになっているので、表示できていないと思われます！

2020-02-14 01:36 UTC, kazu-taka commented on index.php
> +      <?php endif; ?>
@Tekkun-0116 
警告メッセージには直接関係ないですが、pタグの中にulタグは入れてはいけないので、pタグの外に出すようにして下さい！
http://xn--lcki7of.jp/1548/

2020-02-14 01:36 UTC, kazu-taka commented on edit.php
> +    <?php if (count($errors) > 0) : ?>
@Tekkun-0116 
$errorsは編集ボタンを押した時だけ初期化されているので、最初に表示したときには$errorsは初期化されていない(生成されていない)ので、何もないモノに対してcountメソッドを実行しようとして警告が表示されています。
カリキュラムのように `<?php if ($errors) : ?>` にすることで警告はでなくなるかと思います！
`<?php if ($errors) : ?>`は、そのオブジェクトにデータが入っているか入っていないか判断することができます。

2020-02-14 15:14 UTC, kazu-taka requested changes
@Tekkun-0116 
コメントしたので、確認お願いします:bow:

2020-02-14 15:14 UTC, kazu-taka commented on edit.php
> +    $errors['due_date'] = '日付が変更されていません';
@Tekkun-0116 
今回は修正しなくても良いですが、入力フォームで「期限日」としているので、ここも「期限が変更されていません」の方がいいと思います！

2020-02-14 15:14 UTC, kazu-taka commented on edit.php
>    if (empty($errors)) {
@Tekkun-0116 
` $sql = "update plans set title = :title," . "due_date = :due_date" . "update_at = now()" . "where id = :id";`
今回の修正ではないですが、ここは
` $sql = "update plans set title = :title, due_date = :due_date, update_at = now() where id = :id";`
と.で繋げないほうが見やすいですね！
また上記のSQLでうまく更新できてました！？
`due_date = :due_date" . "update_at = now()`の部分ですが、update_atの前に`,`が必用な気がします✨

2020-02-14 15:14 UTC, kazu-taka commented on edit.php
> +    <? endif; ?>
@Tekkun-0116 
`<?php endif: ?>`が正しいです！

2020-02-14 15:14 UTC, kazu-taka commented on index.php
>        <input type="date" name="due_date" id="">
@Tekkun-0116 
ここはlabelタグ使った方がきれいです！
```html
<form action="" method="post">
  <label for="title">学習内容:
    <input type="text" name="title" id="">
  </label>
  <label for="due_date">期限日:
    <input type="date" name="due_date" id="">
  </label>

```

2020-02-14 15:14 UTC, kazu-taka commented on index.php
> +      <? endif; ?>
@Tekkun-0116 
ここもphpは必用です✨

2020-02-14 15:14 UTC, kazu-taka commented on edit.php
> +    $errors['due_date'] = '日付が変更されていません';
@Tekkun-0116 
今の状態だと、 学習内容と期限が未入力でも登録できてしまうので、バリデーション使いした方がよいですね！

2020-02-14 15:14 UTC, kazu-taka commented on edit.php
> +    $errors['title'] = 'タスク名が変更されていません';
@Tekkun-0116 
今回はタスク名ではなく、学習内容の方が統一感があって分かりやすいと思います！

2020-02-18 14:22 UTC, Arisaarisa commented on index.php
> +$sql = "select * from plans where status = 'notyet'";
`昇順`で表示お願いします！

2020-02-18 14:22 UTC, Arisaarisa commented on index.php
> +$sql2 = "select * from plans where status = 'done'";
`降順`で表示お願いします！

2020-02-18 14:22 UTC, Arisaarisa commented on edit.php
> +    $sql = "update plans set title = :title, due_date = :due_date, update_at = now() where id = :id";
`updated_at`の`d`が抜けてるようですが、問題なく編集は更新できていましたか？！
修正後は必ず動作確認してから提出をお願いします( ｀・∀・´)ﾉﾖﾛｼｸ

2020-02-28 01:02 UTC, Arisaarisa commented on index.php
> +  <label for="title">学習内容:
学習内容と期限ですが横並びではなく課題の図のように縦に並ぶようにお願いします！！

2020-02-29 13:19 UTC, Tekkun-0116 commented
修正しました！
修正前
![スクリーンショット 2020-02-29 22 10 58](https://user-images.githubusercontent.com/58411036/75608244-334e6900-5b41-11ea-8d9f-d5243c8f67dd.png)
↓
修正後
![スクリーンショット 2020-02-29 22 16 06](https://user-images.githubusercontent.com/58411036/75608260-4eb97400-5b41-11ea-8b5f-5a94cf81d22f.png)
学習内容のところを縦並びにして、未達成は昇順、達成済みのところを降順にしました。
編集も更新できました！

こちらえ大丈夫でしょうか？

2020-02-29 23:47 UTC, Arisaarisa commented
index.phpの中で
```
  </body>
</html>
```
がなくなってしまっているので修正お願います！！🙏

2020-03-02 06:25 UTC, Arisaarisa reviewed
修正後再度コードを見直しておかしなところがないか確認、実装、スクショして大丈夫そうだったら提出お願いします！

2020-03-02 06:25 UTC, Arisaarisa commented on edit.php
> +      <ul style="color:red;">
ここはcss ファイルにの情報を取れるようにしてください！

2020-03-02 06:25 UTC, Arisaarisa commented on index.php
> +    <ul style="color:red;">
ここもcssファイルから持ってくるようにしましょう！

2020-03-02 06:25 UTC, Arisaarisa commented on edit.php
> +    <input type="text" name="title" id="" value="<?php echo h($plan['title']); ?>">
labelタグでまとめます！
`目標内容:`も表示されるようにてください！

2020-03-02 06:25 UTC, Arisaarisa commented on edit.php
> +    期限日:
due_dateもlabelタグでまとめます！

2020-03-02 07:41 UTC, Tekkun-0116 commented
![スクリーンショット 2020-03-02 16 37 27](https://user-images.githubusercontent.com/58411036/75655125-8a208380-5ca4-11ea-878a-ec9b55bf055c.png)
![スクリーンショット 2020-03-02 16 37 12](https://user-images.githubusercontent.com/58411036/75655129-8db40a80-5ca4-11ea-9ba7-e2ad829ec9a0.png)

度々申し訳ございませんが、確認、実装を確認しました！
こちらの方で問題ありませんでしょうか？

2020-03-03 05:26 UTC, Arisaarisa commented
![LGTM](https://cdn.lgtmoon.dev/images/9646)

2020-03-03 05:54 UTC, merged